services:
  bot:
    build: .
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database/eco
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database/eco
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
