FROM python:3.11-alpine

WORKDIR /app

COPY . .

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --only main

RUN apk add --no-cache just

CMD ["just", "run-admin"]
